
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class ForgetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        jButton2.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jButton4.setVisible(false);
        jLabel11.setVisible(false);
        jPanel2.setBackground(new Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        p1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forget your password ?");

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 26)); // NOI18N
        jLabel1.setText("FORGOT YOUR PASSWORD ?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Admin", "Customer" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 180, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 1, 20)); // NOI18N
        jLabel8.setText("AS*");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel3.setText("WHERE WAS YOUR FIRST VACATION ? (Caps *)");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jTextField1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 188, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel2.setText("USERNAME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jTextField2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 266, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/c2.jpg"))); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 100, -1));

        p1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 190, 30));

        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel4.setText("NEW PASSWORD");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feye2.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feye.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel5.setText("CONFIRM PASSWORD");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        p2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 190, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feye2.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feye.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 51, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sub.png"))); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 51, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lo.jpg"))); // NOI18N
        jButton4.setText("GO TO LOGIN PAGE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 102));
        jLabel11.setText("CHANGE YOUR PASSWORD");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 680, 430));

        jLabel12.setBackground(new java.awt.Color(255, 255, 0));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new think.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 120, 130));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forgetback.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int refer=0;
        if(jComboBox1.getSelectedItem() == "Customer")
            {
                try
                {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarketdb","root","");
                    Statement stmt=con.createStatement();
                    ResultSet rs = stmt.executeQuery("SELECT * FROM customer");
                    while(rs.next())
                    {
                        if(rs.getString(8).equals(jTextField1.getText()))
                        {
                            if(rs.getString(10).equals(jTextField2.getText()))
                            {
                                refer=2;
                                jLabel11.setVisible(true);
                                jLabel4.setVisible(true);
                                jLabel5.setVisible(true);
                                p1.setVisible(true);
                                p2.setVisible(true);
                               jButton4.setVisible(true);
                                jButton2.setVisible(true);
                                jLabel6.setVisible(false);
                                jLabel7.setVisible(true);
                                jLabel9.setVisible(false);
                                jLabel10.setVisible(true); 
                                jLabel8.setVisible(false);
                                jLabel2.setVisible(false);
                                jLabel3.setVisible(false);
                                jButton1.setVisible(false);
                                jComboBox1.setVisible(false);
                                jTextField1.setVisible(false);
                                jTextField2.setVisible(false);
                                break;
                            }
                            else
                            {
                                refer=3;
                                break;
                            }
                        }
                        else
                        {
                            refer=1;
                        }
                    }
                    if(refer==0)
                    {
                        JOptionPane.showMessageDialog(null,"INVALID!!PLEASE CONTACT ADMINISTRATION!");
                    }
                    else if(refer==1)
                    {
                        JOptionPane.showMessageDialog(null,"INVALID USERNAME!!");
                    }
                    else if(refer==3)
                    {
                        JOptionPane.showMessageDialog(null,"WRONG ANSWER!!YOU CAN'T CHANGE YOUR PASSWORD!   ");
                    }
                }
                catch(Exception e)
                {   
                    System.out.println(e);
                }
            }
            else if(jComboBox1.getSelectedItem() == "Admin")
            {
                try
                {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarketdb","root","");
                    Statement stmt=con.createStatement();
                    ResultSet rs = stmt.executeQuery("SELECT * FROM admin");
                    while(rs.next())
                    {
                        if(rs.getString(1).equals(jTextField1.getText()))
                        {
                            if(rs.getString(3).equals(jTextField2.getText()))
                            {
                                refer=2;
                                jLabel11.setVisible(true);
                               jLabel4.setVisible(true);
                                jLabel5.setVisible(true);
                                p1.setVisible(true);
                                p2.setVisible(true);
                                jButton4.setVisible(true);
                                jButton2.setVisible(true);
                                jLabel6.setVisible(false);
                                jLabel7.setVisible(true);
                                jLabel9.setVisible(false);
                                jLabel10.setVisible(true); 
                                jLabel8.setVisible(false);
                                jLabel2.setVisible(false);
                                jLabel3.setVisible(false);
                                jButton1.setVisible(false);
                                jComboBox1.setVisible(false);
                                jTextField1.setVisible(false);
                                jTextField2.setVisible(false);
                                break;
                            }
                            else
                            {
                                refer=3;
                                break;
                            }
                        }
                        else
                        {
                            refer=1;
                        }
                    }
                    if(refer==0)
                    {
                        JOptionPane.showMessageDialog(null,"INVALID!!PLEASE CONTACT ADMINISTRATION!");
                    }
                    else if(refer==1)
                    {
                        JOptionPane.showMessageDialog(null,"INVALID USERNAME!!");
                    }
                    else if(refer==3)
                    {
                        JOptionPane.showMessageDialog(null,"WRONG ANSWER!!YOU CAN'T CHANGE YOUR PASSWORD!   ");
                    }
                }
                catch(Exception e)
                {   
                    System.out.println(e);
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem()=="Customer")
        {
            if(p1.getText().equals(p2.getText()))
            {
                try
                {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarketdb","root","");
                Statement stmt = con.createStatement();
                String q1 = "UPDATE customer SET Password = '" +p1.getText()+ "' WHERE Username = '" +jTextField1.getText()+ "'";
                stmt.executeUpdate(q1);
                JOptionPane.showMessageDialog(null,"Updated Successfully!!");
                }
                catch(Exception e)
                {   
                    System.out.println(e);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"PASSWORD NOT MATCHED!");
            }
        }
        if(jComboBox1.getSelectedItem()=="Admin")
        {
            if(p1.getText().equals(p2.getText()))
            {
                try
                {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarketdb","root","");
                Statement stmt = con.createStatement();
                String q1 = "UPDATE admin SET Password = '" +p1.getText()+ "' WHERE Username = '" +jTextField1.getText()+ "'";
                stmt.executeUpdate(q1);
                JOptionPane.showMessageDialog(null,"Updated Successfully!!");
                }
                catch(Exception e)
                {   
                    System.out.println(e);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"PASSWORD NOT MATCHED!");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
        jLabel6.setVisible(true);
        jLabel10.setVisible(false);
        p1.setEchoChar((char)0);
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        jLabel10.setVisible(true);
        jLabel6.setVisible(false);
        p1.setEchoChar('*');
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        jLabel9.setVisible(true);
        jLabel7.setVisible(false);
        p2.setEchoChar((char)0);
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        jLabel7.setVisible(true);
        jLabel9.setVisible(false);
        p2.setEchoChar('*');
    }//GEN-LAST:event_jLabel9MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        LoginForm l=new LoginForm();
        l.show();
        dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    // End of variables declaration//GEN-END:variables
}
