
import java.awt.Image;
import java.awt.MouseInfo;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.Period;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    int click1=0;
    int click2=0;
    public RegisterForm() {
        initComponents();
        String set = "<html><u>Click Here </u></html>";
        jLabel2.setText(set);
        tf15.setVisible(false);
        tf1.setVisible(false);
        tf16.setVisible(false);
        tf21.setVisible(false);
        tf22.setVisible(false);
        tf5.setVisible(false);
        tf4.setVisible(false);
        tf7.setVisible(false);
        tf6.setVisible(false);
        tf10.setVisible(false);
        tf8.setVisible(false);
        tf20.setVisible(false);
        tf13.setVisible(false);
        tf9.setVisible(false);
        tf12.setVisible(false);
        tf30.setVisible(false);
        tf29.setVisible(false);
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarketdb","root","");
            JOptionPane.showMessageDialog(null,"Loading...");        
        }
        catch(Exception e)                    
        {
          JOptionPane.showMessageDialog(null,"Not Connected");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf15 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf1 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf21 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        JLabel5 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        tf22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf16 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf10 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf8 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf5 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf4 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        padd = new javax.swing.JLabel();
        tf30 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf7 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        tf29 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        tf20 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf13 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton7 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        tf9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        tf12 = new javax.swing.JLabel();
        caps = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        pb1 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("REGISTRATION FORM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 32, 530, 52));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b3.jpg"))); // NOI18N
        jButton2.setText("GO TO HOME PAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1014, 53, -1, -1));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 153));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("FIRST NAME");

        tf15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf15.setForeground(new java.awt.Color(255, 0, 0));
        tf15.setText("*");

        t1.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("LAST NAME");

        tf1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf1.setForeground(new java.awt.Color(255, 0, 0));
        tf1.setText("*");

        t2.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t2KeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("DATE OF BIRTH");

        tf21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf21.setForeground(new java.awt.Color(255, 0, 0));
        tf21.setText("*");

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        JLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        JLabel5.setForeground(new java.awt.Color(0, 0, 102));
        JLabel5.setText("GENDER");

        buttonGroup2.add(rb1);
        rb1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        rb1.setForeground(new java.awt.Color(0, 0, 102));
        rb1.setText("MALE");
        rb1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        buttonGroup2.add(rb2);
        rb2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        rb2.setForeground(new java.awt.Color(0, 0, 102));
        rb2.setText("FEMALE");
        rb2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        tf22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf22.setForeground(new java.awt.Color(255, 0, 0));
        tf22.setText("*");

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("AADHAR CARD ");

        tf16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf16.setForeground(new java.awt.Color(255, 0, 0));
        tf16.setText("*");

        t4.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        t4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t4KeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("MOBILE NO.");

        tf10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf10.setForeground(new java.awt.Color(255, 0, 0));
        tf10.setText("*");

        t7.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        t7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        t7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t7KeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("MAIL ID");

        tf8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf8.setForeground(new java.awt.Color(255, 0, 0));
        tf8.setText("*");

        t8.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        t8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/12345.jpg"))); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(192, 192, 192))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(JLabel5)
                                        .addGap(270, 270, 270)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addGap(192, 192, 192)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(276, 276, 276)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf8)
                            .addComponent(tf10)
                            .addComponent(tf16)
                            .addComponent(tf22)
                            .addComponent(tf21)
                            .addComponent(tf1)
                            .addComponent(tf15))))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(t8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                        .addComponent(t4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t7, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rb1)
                        .addGap(32, 32, 32)
                        .addComponent(rb2)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tf21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(JLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb1)
                            .addComponent(rb2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf22)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tf10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tf8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Basic Details  ", new javax.swing.ImageIcon(getClass().getResource("/images (3).png")), jPanel2); // NOI18N

        jPanel3.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("ADDRESS");

        tf5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf5.setForeground(new java.awt.Color(255, 0, 0));
        tf5.setText("*");

        t5.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        t5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("CITY");

        tf4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf4.setForeground(new java.awt.Color(255, 0, 0));
        tf4.setText("*");

        t6.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        t6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        t6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t6KeyPressed(evt);
            }
        });

        padd.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        padd.setForeground(new java.awt.Color(0, 0, 102));
        padd.setText("PERMANENT ADDRESS");

        tf30.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf30.setForeground(new java.awt.Color(255, 0, 0));
        tf30.setText("*");

        jTextField1.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("PINCODE");

        tf7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf7.setForeground(new java.awt.Color(255, 0, 51));
        tf7.setText("*");

        t9.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        t9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        t9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t9KeyPressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("DISTRICT");

        tf6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf6.setForeground(new java.awt.Color(255, 0, 0));
        tf6.setText("*");

        jTextField6.setFont(new java.awt.Font("Bodoni MT", 0, 20)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1.jpg"))); // NOI18N
        jButton3.setText("GO BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 0, 102));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/12345.jpg"))); // NOI18N
        jButton10.setText("NEXT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel7)
                                    .addComponent(padd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf30, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tf6, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tf4))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tf7)))
                                .addGap(15, 15, 15))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(99, 99, 99)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                        .addComponent(t5))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                        .addComponent(t9, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t6, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton10)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(padd)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf30))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tf4))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton10))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf7))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20)))))
                        .addGap(14, 93, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Residential Details  ", new javax.swing.ImageIcon(getClass().getResource("/download (3).png")), jPanel3); // NOI18N

        jPanel4.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("ID PROOF");

        jTextField2.setFont(new java.awt.Font("Bodoni MT", 0, 16)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        jButton4.setBackground(new java.awt.Color(0, 204, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (8).jpg"))); // NOI18N
        jButton4.setText("Upload");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tf29.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf29.setForeground(new java.awt.Color(255, 0, 0));
        tf29.setText("*");

        jLabel14.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("PHOTO");

        jTextField3.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 0, 0));
        jLabel18.setText("     120x120");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jLabel18.setOpaque(true);

        jButton5.setBackground(new java.awt.Color(0, 0, 102));
        jButton5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attach.png"))); // NOI18N
        jButton5.setText("Attach");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/12345.jpg"))); // NOI18N
        jButton6.setText("NEXT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(0, 0, 102));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1.jpg"))); // NOI18N
        jButton12.setText("GO BACK");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(504, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(382, 382, 382))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 225, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(143, 143, 143))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(tf29)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jButton12)
                .addGap(186, 186, 186)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf29))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton12))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Document Upload  ", new javax.swing.ImageIcon(getClass().getResource("/download (4).png")), jPanel4); // NOI18N

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("USERNAME");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 66, -1, -1));

        tf20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf20.setForeground(new java.awt.Color(255, 0, 0));
        tf20.setText("*");
        jPanel5.add(tf20, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 57, -1, -1));

        jTextField4.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 61, 263, 33));

        jLabel16.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("PASSWORD");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 117, -1, 37));

        tf13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf13.setForeground(new java.awt.Color(255, 0, 0));
        tf13.setText("*");
        jPanel5.add(tf13, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 117, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jPanel5.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 117, 263, 37));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-eye-32.png"))); // NOI18N
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 117, 40, 30));

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("CONFIRM PASSWORD");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 172, -1, -1));

        jPasswordField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jPanel5.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 178, 263, 32));

        tf9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf9.setForeground(new java.awt.Color(255, 0, 0));
        tf9.setText("*");
        jPanel5.add(tf9, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 175, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-eye-32.png"))); // NOI18N
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton8MousePressed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 175, 40, 30));

        jLabel19.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("WHERE WAS YOUR FIRST VACATION ? ");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 240, -1, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 289, 392, 38));

        tf12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tf12.setForeground(new java.awt.Color(255, 0, 0));
        tf12.setText("* ");
        jPanel5.add(tf12, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 289, -1, -1));

        caps.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        caps.setForeground(new java.awt.Color(255, 0, 0));
        caps.setText("Caps*");
        jPanel5.add(caps, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 242, -1, -1));

        jButton9.setBackground(new java.awt.Color(0, 0, 102));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b4.jpg"))); // NOI18N
        jButton9.setText("SUBMIT");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, -1, 50));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 0, 102));
        jLabel21.setText("Remember this answer , it will help you when you forget the password");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 339, 470, -1));

        jCheckBox1.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Accept the terms and conditions.");
        jPanel5.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 378, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Click Here");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 377, -1, -1));

        jButton11.setBackground(new java.awt.Color(0, 0, 102));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1.jpg"))); // NOI18N
        jButton11.setText("GO BACK");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, 50));

        jTabbedPane1.addTab("Create Account  ", new javax.swing.ImageIcon(getClass().getResource("/images (6).png")), jPanel5); // NOI18N

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 1090, 520));

        pb1.setBackground(new java.awt.Color(255, 255, 255));
        pb1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pb1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(pb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 64, 180, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("FILLING STATUS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 100, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backreg.png"))); // NOI18N
        jLabel22.setText("jLabel22");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1340, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            t1.setEditable(true);
        }
        else
        {
            t1.setEditable(false);
        }
    }//GEN-LAST:event_t1KeyPressed

    private void t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            t2.setEditable(true);
        }
        else
        {
            t2.setEditable(false);
        }
    }//GEN-LAST:event_t2KeyPressed

    private void t4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String a = t4.getText();
        int len = a.length();
        if(Character.isDigit(c))
        {
            if(len<12)
            {
                t4.setEditable(true);
            }
            else
            {
                t4.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==evt.VK_BACK_SPACE || evt.getExtendedKeyCode()==evt.VK_DELETE)
            {
                t4.setEditable(true);
            }
            else
            {
                t4.setEditable(false);
            }
        }
    }//GEN-LAST:event_t4KeyPressed

    private void t7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t7KeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String a = t7.getText();
        int len = a.length();
        if(Character.isDigit(c))
        {
            if(len<10)
            {
                t7.setEditable(true);
            }
            else
            {
                t7.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==evt.VK_BACK_SPACE || evt.getExtendedKeyCode()==evt.VK_DELETE)
            {
                t7.setEditable(true);
            }
            else
            {
                t7.setEditable(false);
            }
        }
    }//GEN-LAST:event_t7KeyPressed

    private void t6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t6KeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            t6.setEditable(true);
        }
        else
        {
            t6.setEditable(false);
        }
    }//GEN-LAST:event_t6KeyPressed

    private void t9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t9KeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String a = t9.getText();
        int len = a.length();
        if(Character.isDigit(c))
        {
            if(len<6)
            {
                t9.setEditable(true);
            }
            else
            {
                t9.setEditable(false);
            }
        }
        else
        {
            if(evt.getExtendedKeyCode()==evt.VK_BACK_SPACE || evt.getExtendedKeyCode()==evt.VK_DELETE)
            {
                t9.setEditable(true);
            }
            else
            {
                t9.setEditable(false);
            }
        }
    }//GEN-LAST:event_t9KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
        {
            jTextField6.setEditable(true);
        }
        else
        {
            jTextField6.setEditable(false);
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        jTextField2.setText(filename);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        jTextField3.setText(filename);
        Image getAbsolutePath = null;
        ImageIcon icon = new ImageIcon(filename);
        Image image=icon.getImage().getScaledInstance(jLabel18.getWidth(),jLabel18.getHeight(),Image.SCALE_SMOOTH);
        jLabel18.setIcon(icon);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        // TODO add your handling code here:

        if(click1%2==0)
        {  jPasswordField1.setEchoChar((char)0);
        }
        else
        jPasswordField1.setEchoChar('*');
        click1++;
    }//GEN-LAST:event_jButton7MousePressed

    private void jButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MousePressed
        // TODO add your handling code here:
        if(click2%2==0)
        {  jPasswordField2.setEchoChar((char)0);
        }
        else
        jPasswordField2.setEchoChar('*');
        click2++;
    }//GEN-LAST:event_jButton8MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int p=pb1.getValue();
        if(t1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"FirstName Field is Empty! Fill it!");
            tf15.setVisible(true);
        }
        else if(t2.getText().trim().isEmpty())
        {
            tf15.setVisible(false);
            JOptionPane.showMessageDialog(null,"LastName Field is Empty! Fill it!");
            tf1.setVisible(true);
        }
        else if(jDateChooser1.getDate()== null)
        {
            tf15.setVisible(false);
            tf1.setVisible(false);
            JOptionPane.showMessageDialog(null,"Date of Birth Field is Empty! Fill it!");
            tf21.setVisible(true);
        }
        else if(buttonGroup2.getSelection()==null)
        {
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf21.setVisible(false);
            JOptionPane.showMessageDialog(null,"Gender Field is Empty! Fill it!");
            tf22.setVisible(true);
        }
        else if(t4.getText().trim().isEmpty())
        {
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf21.setVisible(false);
            tf22.setVisible(false);
            JOptionPane.showMessageDialog(null,"Aadhar Field is Empty! Fill it!");
            tf16.setVisible(true);
        }
        else if(t7.getText().trim().isEmpty())
        {
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf21.setVisible(false);
            tf22.setVisible(false);
            tf16.setVisible(false);
            JOptionPane.showMessageDialog(null,"Mobile Number Field is Empty! Fill it!");
            tf10.setVisible(true);
        }
        else if(t8.getText().trim().isEmpty())
        {
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf21.setVisible(false);
            tf22.setVisible(false);
            tf16.setVisible(false);
            tf10.setVisible(false);
            JOptionPane.showMessageDialog(null,"Mail ID Field is Empty! Fill it!");
            tf8.setVisible(true);
        }
        else if(t4.getText().length() != 12)
        {
            JOptionPane.showMessageDialog(null,"Aadhar Field is in Invalid Length!");
        }
        else if(t7.getText().length() != 10)
        {
            JOptionPane.showMessageDialog(null,"Mobile Number Field is in Invalid Length!");
        }
        else
        {
            pb1.setValue(p+35);
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf16.setVisible(false);
            tf21.setVisible(false);
            tf22.setVisible(false);
            tf10.setVisible(false);
            tf8.setVisible(false);
            jTabbedPane1.setSelectedIndex(1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int p=pb1.getValue();
        if(jTextField4.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"UserName Field is Mandatory! Fill it!");
            tf20.setVisible(true);
        }
        else if(jPasswordField1.getText().trim().isEmpty())
        {
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf16.setVisible(false);
            tf21.setVisible(false);
            tf22.setVisible(false);
            tf10.setVisible(false);
            tf8.setVisible(false);
            tf5.setVisible(false);
            tf30.setVisible(false);
            tf4.setVisible(false);
            tf7.setVisible(false);
            tf6.setVisible(false);
            tf29.setVisible(false);
            tf20.setVisible(false);
            JOptionPane.showMessageDialog(null,"Password Field is Mandatory! Fill it!");
            tf13.setVisible(true);
        }
        else if(jPasswordField2.getText().trim().isEmpty())
        {
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf16.setVisible(false);
            tf21.setVisible(false);
            tf22.setVisible(false);
            tf10.setVisible(false);
            tf8.setVisible(false);
            tf5.setVisible(false);
            tf30.setVisible(false);
            tf4.setVisible(false);
            tf7.setVisible(false);
            tf6.setVisible(false);
            tf29.setVisible(false);
            tf20.setVisible(false);
            tf13.setVisible(false);
            JOptionPane.showMessageDialog(null,"Confirm your Password! Fill it!");
            tf9.setVisible(true);
        }
        else if(jTextField5.getText().trim().isEmpty())
        {
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf16.setVisible(false);
            tf21.setVisible(false);
            tf22.setVisible(false);
            tf10.setVisible(false);
            tf8.setVisible(false);
            tf5.setVisible(false);
            tf30.setVisible(false);
            tf4.setVisible(false);
            tf7.setVisible(false);
            tf6.setVisible(false);
            tf29.setVisible(false);
            tf20.setVisible(false);
            tf13.setVisible(false);
            tf9.setVisible(false);
            JOptionPane.showMessageDialog(null,"Answer the question ask by us! Fill it!");
            tf12.setVisible(true);
        }
        else if(!jPasswordField1.getText().equals(jPasswordField2.getText()))
        {
            JOptionPane.showMessageDialog(null,"Password Field is not matched!");
        }
        else
        {
            int ref=0;
            if(!t4.getText().trim().isEmpty())
            {
                try
                {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarketdb","root","");
                Statement stmt=con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM customer");
                while(rs.next())
                {
                    if(rs.getString(4).equals(t4.getText()))
                    {
                         ref=1;
                        JOptionPane.showMessageDialog(null,"ALREADY REGISTERED!! JUST LOGIN!!");
                        break;
                    }
                }
                }
            
                catch(Exception e)
                {
                        System.out.println(e);
                }
            }
            if(!jTextField4.getText().trim().isEmpty() && ref!=1)
            {
                try
                {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarketdb","root","");
                Statement stmt=con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM customer");
                while(rs.next())
                {
                    if(rs.getString(8).equals(jTextField4.getText()))
                    {
                        ref=2;
                        JOptionPane.showMessageDialog(null,"USERNAME ALREADY TAKEN!! CHOOSE ANOTHER!!");
                        break;
                    }
                }
                }
            
                catch(Exception e)
                {
                        System.out.println(e);
                } 
                }
            if(ref!=1 && ref!=2)
            {
                pb1.setValue(p+20);
            if(jCheckBox1.isSelected())
            {
                String s1=t1.getText();
                String s2=t2.getText();
                String name = s1 + " " + s2;
                String c = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
                String dob[]=c.split("/");
                int date = Integer.parseInt(dob[0]);
                int month = Integer.parseInt(dob[1]);
                int year = Integer.parseInt(dob[2]);
                LocalDate selectedDate = LocalDate.of(year,month,date);
                LocalDate currentDate = LocalDate.now();
                int resultYear = Period.between(selectedDate,currentDate).getYears();
                String Age=String.valueOf(resultYear);
                String aadhar=t4.getText();
                String gender;
                if (rb1.isSelected())
                gender="MALE";
                else if(rb2.isSelected())
                gender="FEMALE";
                else
                gender="NULL";
                String mobile = t7.getText();
                String mail = t8.getText();
                String address = t5.getText();
                String city = t6.getText();
                String pincode = t9.getText();
                String dist = jTextField6.getText();
                String doc=jTextField2.getText();
                doc=doc.replace("\\","\\\\");
                String image = jTextField3.getText();
                image = image.replace("\\", "\\\\");
                if(jTextField3.getText().trim().isEmpty())
                {
                    image="0";
                }
                String padd=jTextField1.getText();
                String uname = jTextField4.getText();
                String pwd = jPasswordField1.getText();
                String fpwd = jTextField5.getText();
                String id=String.valueOf(CusKey());
                String taddress = address + "," + city + " - " + pincode + "," + dist ;
                String query="0";
                String reply="0";
                String feedback="0";
                try
                {
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarketdb","root","");
                        Statement stmt = con.createStatement();
                        // Inserting data in database
                        String q1 = "insert into customer values('" +name+"','"+Age+"','"+gender+"','"+aadhar+"','"+taddress+"','"+mobile+"','"+mail+"','"+uname+"','"+pwd+"','"+fpwd+"','"+doc+"','"+image+"','"+padd+"','"+id+"','"+query+"','"+reply+"','"+feedback+"')";
                        stmt.executeUpdate(q1);
                        JOptionPane.showMessageDialog(null,"REGISTERED SUCCESSFULLY!!  LOGIN NOW!!");
                        LoginForm l=new LoginForm();
                        l.show();
                        dispose();
                }
                catch(Exception e)
                {
                        System.out.println(e);
                }
              
            
            }
                else
                {
                    JOptionPane.showMessageDialog(null,"Please accept the terms and conditions.");
                }
         }
        }           
    }//GEN-LAST:event_jButton9ActionPerformed
    public int CusKey()
    {
        Random r = new Random();
        int id=r.nextInt(100,500);
        String ID=String.valueOf(id);
        try
        {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarketdb","root","");
                Statement stmt=con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM customer");
                while(rs.next())
                {
                   if(rs.getString(14).equals(ID))
                   {
                      CusKey();
                      return 0;
                   }
                }
        }
        catch(Exception e)
        {
                System.out.println(e);
        }
        return id;
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int p=pb1.getValue();
        if(t5.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Address Field is Empty! Fill it!");
            tf5.setVisible(true);
        }
        else if(jTextField1.getText().trim().isEmpty())
        {
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf16.setVisible(false);
            tf21.setVisible(false);
            tf22.setVisible(false);
            tf10.setVisible(false);
            tf8.setVisible(false);
            tf5.setVisible(false);
            JOptionPane.showMessageDialog(null,"Permanent Address Field is Empty! Fill it!");
            tf30.setVisible(true);
        }
        else if(t6.getText().trim().isEmpty())
        {
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf16.setVisible(false);
            tf21.setVisible(false);
            tf22.setVisible(false);
            tf10.setVisible(false);
            tf8.setVisible(false);
            tf5.setVisible(false);
            tf30.setVisible(false);
            JOptionPane.showMessageDialog(null,"City Field is Empty! Fill it!");
            tf4.setVisible(true);
        }
        else if(t9.getText().trim().isEmpty())
        {
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf16.setVisible(false);
            tf21.setVisible(false);
            tf22.setVisible(false);
            tf10.setVisible(false);
            tf8.setVisible(false);
            tf5.setVisible(false);
            tf30.setVisible(false);
            tf4.setVisible(false);
            JOptionPane.showMessageDialog(null,"Pincode Field is Empty! Fill it!");
            tf7.setVisible(true);
        }
        else if(jTextField6.getText().trim().isEmpty())
        {
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf16.setVisible(false);
            tf21.setVisible(false);
            tf22.setVisible(false);
            tf10.setVisible(false);
            tf8.setVisible(false);
            tf5.setVisible(false);
            tf30.setVisible(false);
            tf4.setVisible(false);
            tf7.setVisible(false);
            JOptionPane.showMessageDialog(null,"District Field is Empty! Fill it!");
            tf6.setVisible(true);
        }
        else if(t9.getText().length() != 6)
        {
            JOptionPane.showMessageDialog(null,"Pincode Field is in Invalid Length!");
        }
        else
        {
            pb1.setValue(p+38);
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf16.setVisible(false);
            tf21.setVisible(false);
            tf22.setVisible(false);
            tf10.setVisible(false);
            tf8.setVisible(false);
            tf5.setVisible(false);
            tf30.setVisible(false);
            tf4.setVisible(false);
            tf7.setVisible(false);
            tf6.setVisible(false);
            jTabbedPane1.setSelectedIndex(2);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int p =pb1.getValue();
        if(jTextField2.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please Upload the ID proof document!");
            tf29.setVisible(true);
        }
        else
        {
            pb1.setValue(p+7);
            tf15.setVisible(false);
            tf1.setVisible(false);
            tf16.setVisible(false);
            tf21.setVisible(false);
            tf22.setVisible(false);
            tf10.setVisible(false);
            tf8.setVisible(false);
            tf5.setVisible(false);
            tf30.setVisible(false);
            tf4.setVisible(false);
            tf7.setVisible(false);
            tf6.setVisible(false);
            tf29.setVisible(false);
            jTabbedPane1.setSelectedIndex(3);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Home h= new Home();
        h.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        TermsAndConditions t = new TermsAndConditions();
        t.show();
    }//GEN-LAST:event_jLabel2MousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel5;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel caps;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel padd;
    private javax.swing.JProgressBar pb1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    public javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JLabel tf1;
    private javax.swing.JLabel tf10;
    private javax.swing.JLabel tf12;
    private javax.swing.JLabel tf13;
    private javax.swing.JLabel tf15;
    private javax.swing.JLabel tf16;
    private javax.swing.JLabel tf20;
    private javax.swing.JLabel tf21;
    private javax.swing.JLabel tf22;
    private javax.swing.JLabel tf29;
    private javax.swing.JLabel tf30;
    private javax.swing.JLabel tf4;
    private javax.swing.JLabel tf5;
    private javax.swing.JLabel tf6;
    private javax.swing.JLabel tf7;
    private javax.swing.JLabel tf8;
    private javax.swing.JLabel tf9;
    // End of variables declaration//GEN-END:variables
}
